package com.bachar.law.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgreementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgreementAllPropertiesEquals(Agreement expected, Agreement actual) {
        assertAgreementAutoGeneratedPropertiesEquals(expected, actual);
        assertAgreementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgreementAllUpdatablePropertiesEquals(Agreement expected, Agreement actual) {
        assertAgreementUpdatableFieldsEquals(expected, actual);
        assertAgreementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgreementAutoGeneratedPropertiesEquals(Agreement expected, Agreement actual) {
        assertThat(actual)
            .as("Verify Agreement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgreementUpdatableFieldsEquals(Agreement expected, Agreement actual) {
        assertThat(actual)
            .as("Verify Agreement relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgreementUpdatableRelationshipsEquals(Agreement expected, Agreement actual) {
        // empty method
    }
}
