version: '3.8'

services:
  app:
    image: bacharlaw
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/bacharLaw
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/bacharLaw
    ports:
      - 127.0.0.1:9090:9090
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/management/health']
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    image: custom-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bacharLaw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
